In [2]:
#Required Packages

import dlib
import cv2
from imutils import face_utils
from scipy.spatial import distance 
import math
import pandas as pd
import numpy as np

from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, roc_auc_score, f1_score
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import warnings
from sklearn import preprocessing

p = "facial-landmarks-recognition-master/shape_predictor_68_face_landmarks.dat"
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(p)

In [3]:
#Feature Functions

def eye_aspect_ratio(eye):
	A = distance.euclidean(eye[1], eye[5])
	B = distance.euclidean(eye[2], eye[4])
	C = distance.euclidean(eye[0], eye[3])
	ear = (A + B) / (2.0 * C)
	return ear

def mouth_aspect_ratio(mouth):
    A = distance.euclidean(mouth[14], mouth[18])
    C = distance.euclidean(mouth[12], mouth[16])
    mar = (A ) / (C)
    return mar

def circularity(eye):
    A = distance.euclidean(eye[1], eye[4])
    radius  = A/2.0
    Area = math.pi * (radius ** 2)
    p = 0
    p += distance.euclidean(eye[0], eye[1])
    p += distance.euclidean(eye[1], eye[2])
    p += distance.euclidean(eye[2], eye[3])
    p += distance.euclidean(eye[3], eye[4])
    p += distance.euclidean(eye[4], eye[5])
    p += distance.euclidean(eye[5], eye[0])
    return 4 * math.pi * Area /(p**2)

def mouth_over_eye(eye):
    ear = eye_aspect_ratio(eye)
    mar = mouth_aspect_ratio(eye)
    mouth_eye = mar/ear
    return mouth_eye


def average(y_pred):
    for i in range(len(y_pred)-1):
        if i % 240 == 0 or (i+1) % 240 == 0:
            pass
        else: 
            average = float(y_pred[i-1] +  y_pred[i] + y_pred[i+1])/3
            if average >= 0.5:
                y_pred[i] = 1
            else:
                y_pred[i] = 0
    return y_pred

In [4]:
#Read in the Data file to Train Model
df = pd.read_csv('Advanced_Drowsiness_Detection-main/data_drowsiness/prepared/totalwithmaininfo.csv',sep=',')
print(df.info)
#df = df.drop(df.columns[0],axis=1)

train_percentage = 17/22
train_index = int(len(df)*train_percentage)
test_index = len(df)-train_index

df_train = df[:train_index]
df_test = df[-test_index:]

df_train

<bound method DataFrame.info of           Y       MOE  Participant       EAR       MAR  Circularity  \
0       0.0  2.534145          1.0  0.312688  0.792397     0.432896   
1       0.0  2.379947          1.0  0.321940  0.766199     0.486923   
2       0.0  2.078550          1.0  0.331216  0.688449     0.456029   
3       0.0  2.509767          1.0  0.309246  0.776136     0.452655   
4       0.0  3.586821          1.0  0.204691  0.734189     0.361123   
...     ...       ...          ...       ...       ...          ...   
17310  10.0  5.349703         63.0  0.181047  0.968549     0.314714   
17311  10.0  5.530147         63.0  0.178874  0.989198     0.306021   
17312  10.0  5.536179         63.0  0.180700  1.000386     0.315374   
17313  10.0  5.472988         63.0  0.181437  0.993005     0.321619   
17314  10.0  6.011408         63.0  0.171145  1.028824     0.299138   

           EAR_N     MAR_N  Circularity_N     MOE_N  
0      -0.999551  0.802437      -0.948848  0.877172  
1      

Y       MOE  Participant       EAR       MAR  Circularity      EAR_N  \
0      0.0  2.534145          1.0  0.312688  0.792397     0.432896  -0.999551   
1      0.0  2.379947          1.0  0.321940  0.766199     0.486923  -0.000897   
2      0.0  2.078550          1.0  0.331216  0.688449     0.456029   1.000448   
3      0.0  2.509767          1.0  0.309246  0.776136     0.452655  -1.371052   
4      0.0  3.586821          1.0  0.204691  0.734189     0.361123 -12.657205   
...    ...       ...          ...       ...       ...          ...        ...   
13374  0.0  3.777925         62.0  0.257295  0.972041     0.433210   2.533460   
13375  0.0  3.447914         62.0  0.280717  0.967887     0.441474   3.037513   
13376  0.0  3.518344         62.0  0.273403  0.961925     0.429112   2.880112   
13377  0.0  3.378880         62.0  0.287726  0.972192     0.439097   3.188368   
13378  0.0  4.336701         62.0  0.246587  1.069373     0.397454   2.303011   

          MAR_N  Circularity_N     MOE_N  
0      0.802437      -0.948848  0.877172  
1      0.317858       1.044306  0.211742  
2     -1.120295      -0.095458 -1.088914  
3      0.501666      -0.219920  0.771970  
4     -0.274242      -3.596686  5.419921  
...         ...            ...       ...  
13374  0.766216       3.853706 -1.304307  
13375  0.661365       4.112333 -1.417143  
13376  0.510907       3.725419 -1.393062  
13377  0.770027       4.037952 -1.440747  
13378  3.222539       2.734593 -1.113252  

[13379 rows x 10 columns]

In [5]:
X_test = df_test.drop('Y',axis = 1)
y_test = df_test["Y"]

X_train = df_train.drop('Y',axis=1)
y_train = df_train['Y']

In [6]:
#KNN

acc3_list = []
f1_score3_list = []
roc_3_list = []
from sklearn.neighbors import KNeighborsClassifier
for i in range(1,30):
    neigh = KNeighborsClassifier(n_neighbors=i)
    neigh.fit(X_train, y_train) 
    pred_KN = neigh.predict(X_test)
    #pKN = np.mean(pred_KN)
    #print(pred_KN.shape)
    #pred_KN2 = np.array([pKN for i in pred_KN])
    #print(pred_KN2)
    pred_KN = average(pred_KN)
    print(pred_KN)
    y_score_3 = neigh.predict_proba(X_test)[:,1]
    acc3_list.append(accuracy_score(y_test, pred_KN))
    f1_score3_list.append(metrics.f1_score(y_test, pred_KN, average = None))
    roc_3_list.append(metrics.roc_auc_score(y_test, y_score_3))
    
    
neigh = KNeighborsClassifier(n_neighbors=acc3_list.index(max(acc3_list))+1)
neigh.fit(X_train, y_train) 
pred_KN = neigh.predict(X_test)
pred_KN = average(pred_KN)
y_score_3 = neigh.predict_proba(X_test)[:,1]
acc3 = accuracy_score(y_test, pred_KN)
f1_score_3 = metrics.f1_score(y_test, pred_KN, average = None)
roc_3 = metrics.roc_auc_score(y_test, y_score_3)
print([acc3,f1_score_3,roc_3])
print(confusion_matrix(y_test, pred_KN))

[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0. 0. 0. ... 1. 1. 0.]
[0.4065040650406504, array([0.62490211, 0.        , 0.00368664]), 0.5]
[[1596  174    0]
 [   0    0    0]
 [1742  420    4]]


In [7]:
def model(landmarks):

    features = pd.DataFrame(columns=["EAR","MAR","Circularity","MOE"])

    eye = landmarks[36:68]
    ear = eye_aspect_ratio(eye)
    mar = mouth_aspect_ratio(eye)
    cir = circularity(eye)
    mouth_eye = mouth_over_eye(eye)

    df = features.append({"EAR":ear,"MAR": mar,"Circularity": cir,"MOE": mouth_eye},ignore_index=True)

    df["EAR_N"] = (df["EAR"]-mean["EAR"])/ std["EAR"]
    df["MAR_N"] = (df["MAR"]-mean["MAR"])/ std["MAR"]
    df["Circularity_N"] = (df["Circularity"]-mean["Circularity"])/ std["Circularity"]
    df["MOE_N"] = (df["MOE"]-mean["MOE"])/ std["MOE"]
    
    Result = neigh.predict(df)
    if Result == 1:
        Result_String = "Drowsy"
    else:
        Result_String = "Alert"
    

    return Result_String, df.values

In [8]:
def video_stream():
    js = Javascript('''
      var video;
      var div = null;
      var stream;
      var captureCanvas;
      var imgElement;
      var labelElement;
    
    var pendingResolve = null;
    var shutdown = false;
    
    function removeDom() {
       stream.getVideoTracks()[0].stop();
       video.remove();
       div.remove();
       video = null;
       div = null;
       stream = null;
       imgElement = null;
       captureCanvas = null;
       labelElement = null;
    }
    
    function onAnimationFrame() {
      if (!shutdown) {
        window.requestAnimationFrame(onAnimationFrame);
      }
      if (pendingResolve) {
        var result = "";
        if (!shutdown) {
          captureCanvas.getContext('2d').drawImage(video, 0, 0, 640, 480);
          result = captureCanvas.toDataURL('image/jpeg', 0.8)
        }
        var lp = pendingResolve;
        pendingResolve = null;
        lp(result);
      }
    }
    
    async function createDom() {
      if (div !== null) {
        return stream;
      }

      div = document.createElement('div');
      div.style.border = '2px solid black';
      div.style.padding = '3px';
      div.style.width = '100%';
      div.style.maxWidth = '600px';
      document.body.appendChild(div);
      
      const modelOut = document.createElement('div');
      modelOut.innerHTML = "<span>Status:</span>";
      labelElement = document.createElement('span');
      labelElement.innerText = 'No data';
      labelElement.style.fontWeight = 'bold';
      modelOut.appendChild(labelElement);
      div.appendChild(modelOut);
           
      video = document.createElement('video');
      video.style.display = 'block';
      video.width = div.clientWidth - 6;
      video.setAttribute('playsinline', '');
      video.onclick = () => { shutdown = true; };
      stream = await navigator.mediaDevices.getUserMedia(
          {video: { facingMode: "environment"}});
      div.appendChild(video);

      imgElement = document.createElement('img');
      imgElement.style.position = 'absolute';
      imgElement.style.zIndex = 1;
      imgElement.onclick = () => { shutdown = true; };
      div.appendChild(imgElement);
      
      const instruction = document.createElement('div');
      instruction.innerHTML = 
          '<span style="color: red; font-weight: bold;">' +
          'When finished, click here or on the video to stop this demo</span>';
      div.appendChild(instruction);
      instruction.onclick = () => { shutdown = true; };
      
      video.srcObject = stream;
      await video.play();

      captureCanvas = document.createElement('canvas');
      captureCanvas.width = 640; //video.videoWidth;
      captureCanvas.height = 480; //video.videoHeight;
      window.requestAnimationFrame(onAnimationFrame);
      
      return stream;
    }
    async function stream_frame(label, imgData) {
      if (shutdown) {
        removeDom();
        shutdown = false;
        return '';
      }

      var preCreate = Date.now();
      stream = await createDom();
      
      var preShow = Date.now();
      if (label != "") {
        labelElement.innerHTML = label;
      }
            
      if (imgData != "") {
        var videoRect = video.getClientRects()[0];
        imgElement.style.top = videoRect.top + "px";
        imgElement.style.left = videoRect.left + "px";
        imgElement.style.width = videoRect.width + "px";
        imgElement.style.height = videoRect.height + "px";
        imgElement.src = imgData;
      }
      
      var preCapture = Date.now();
      var result = await new Promise(function(resolve, reject) {
        pendingResolve = resolve;
      });
      shutdown = false;
      
      return {'create': preShow - preCreate, 
              'show': preCapture - preShow, 
              'capture': Date.now() - preCapture,
              'img': result};
    }
    ''')

  display(js)
  
def video_frame(label, bbox):
  data = eval_js('stream_frame("{}", "{}")'.format(label, bbox))
  return data

In [9]:
def calibration():
    data = []
    cap = cv2.VideoCapture(0)

    while True:
        # Getting out image by webcam 
        _, image = cap.read()
        # Converting the image to gray scale
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # Get faces into webcam's image
        rects = detector(image, 0)

        # For each detected face, find the landmark.
        for (i, rect) in enumerate(rects):
            # Make the prediction and transfom it to numpy array
            shape = predictor(gray, rect)
            shape = face_utils.shape_to_np(shape)
            data.append(shape)
            cv2.putText(image,"Calibrating...", bottomLeftCornerOfText, font, fontScale, fontColor,lineType)

            # Draw on our image, all the finded cordinate points (x,y) 
            for (x, y) in shape:
                cv2.circle(image, (x, y), 2, (0, 255, 0), -1)

        # Show the image
        cv2.imshow("Output", image)

        k = cv2.waitKey(5) & 0xFF
        if k == 27:
            break

    cv2.destroyAllWindows()
    cap.release()
    
    
    features_test = []
    for d in data:
        eye = d[36:68]
        ear = eye_aspect_ratio(eye)
        mar = mouth_aspect_ratio(eye)
        cir = circularity(eye)
        mouth_eye = mouth_over_eye(eye)
        features_test.append([ear, mar, cir, mouth_eye])
    
    features_test = np.array(features_test)
    x = features_test
    y = pd.DataFrame(x,columns=["EAR","MAR","Circularity","MOE"])
    df_means = y.mean(axis=0)
    df_std = y.std(axis=0)
    
    return df_means,df_std

font                   = cv2.FONT_HERSHEY_SIMPLEX
bottomLeftCornerOfText = (10,400)
fontScale              = 1
fontColor              = (255,255,255)
lineType               = 2

In [10]:
data=  []
image = "311920098_2941470226158522_4389840814121507504_n.jpg"
img = cv2.imread(image)
#gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

# Get faces into webcam's image
rects = detector(img, 0)

# For each detected face, find the landmark.
for (i, rect) in enumerate(rects):
    # Make the prediction and transfom it to numpy array
    shape = predictor(img, rect)
    shape = face_utils.shape_to_np(shape)
    print(shape)
    data.append(shape)
    cv2.putText(img,"Calibrating...", bottomLeftCornerOfText, font, fontScale, fontColor,lineType)

    # Draw on our image, all the finded cordinate points (x,y) 
    for (x, y) in shape:
        cv2.circle(img, (x, y), 2, (0, 255, 0), -1) #2048 1536

# Show the image
cv2.imshow('image',img)

[[1294  834]
 [1294  890]
 [1300  945]
 [1313  999]
 [1336 1050]
 [1373 1096]
 [1417 1136]
 [1467 1171]
 [1530 1184]
 [1594 1175]
 [1649 1142]
 [1694 1101]
 [1731 1054]
 [1751  999]
 [1760  940]
 [1764  882]
 [1763  823]
 [1327  788]
 [1355  759]
 [1396  749]
 [1440  757]
 [1483  773]
 [1553  769]
 [1594  752]
 [1637  740]
 [1680  745]
 [1711  773]
 [1518  811]
 [1518  842]
 [1518  871]
 [1518  903]
 [1465  943]
 [1493  948]
 [1520  953]
 [1546  948]
 [1572  943]
 [1374  824]
 [1398  816]
 [1424  813]
 [1452  822]
 [1425  827]
 [1399  829]
 [1584  818]
 [1612  807]
 [1638  807]
 [1665  814]
 [1639  820]
 [1613  820]
 [1422 1019]
 [1457 1000]
 [1491  987]
 [1514  993]
 [1538  988]
 [1578 1004]
 [1619 1026]
 [1579 1047]
 [1542 1058]
 [1516 1059]
 [1490 1056]
 [1458 1043]
 [1438 1021]
 [1491 1019]
 [1515 1021]
 [1540 1021]
 [1602 1026]
 [1540 1021]
 [1515 1022]
 [1492 1020]]
[[ 615  954]
 [ 618  982]
 [ 622 1009]
 [ 628 1037]
 [ 639 1065]
 [ 659 1087]
 [ 689 1102]
 [ 721 1113]
 [ 758 1113

In [11]:
def live():
    cap = cv2.VideoCapture(0)
    data = []
    result = []
    while True:
        # Getting out image by webcam 
        _, image = cap.read()
        # Converting the image to gray scale
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # Get faces into webcam's image
        rects = detector(image, 0)

        # For each detected face, find the landmark.
        for (i, rect) in enumerate(rects):
            # Make the prediction and transfom it to numpy array
            shape = predictor(gray, rect)
            shape = face_utils.shape_to_np(shape)
            Result_String, features = model(shape)
            cv2.putText(image,Result_String, bottomLeftCornerOfText, font, fontScale, fontColor,lineType)
            data.append (features)
            result.append(Result_String)

            # Draw on our image, all the finded cordinate points (x,y) 
            for (x, y) in shape:
                cv2.circle(image, (x, y), 2, (0, 255, 0), -1)

        # Show the image
        cv2.imshow("Output", image)

        k = cv2.waitKey(300) & 0xFF
        if k == 27:
            break

    cv2.destroyAllWindows()
    cap.release()
    
    return data,result

font                   = cv2.FONT_HERSHEY_SIMPLEX
bottomLeftCornerOfText = (10,400)
fontScale              = 1
fontColor              = (255,255,255)
lineType               = 2

In [12]:
def js_to_image(js_reply):
  """
  Params:
          js_reply: JavaScript object containing image from webcam
  Returns:
          img: OpenCV BGR image
  """
  # decode base64 image
  image_bytes = b64decode(js_reply.split(',')[1])
  # convert bytes to numpy array
  jpg_as_np = np.frombuffer(image_bytes, dtype=np.uint8)
  # decode numpy array into OpenCV BGR image
  img = cv2.imdecode(jpg_as_np, flags=1)

  return img

In [13]:
# start streaming video from webcam
video_stream()
# label for video
label_html = 'Capturing...'
# initialze bounding box to empty
bbox = ''
count = 0 
while True:
    js_reply = video_frame(label_html, bbox)
    if not js_reply:
        break
    frame = js_to_image(js_reply["img"])
    print(frame)
    gray = cv2.imread(js_reply)
    #gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

    # Get faces into webcam's image
    rects = detector(gray, 0)

    # For each detected face, find the landmark.
    for (i, rect) in enumerate(rects):
        # Make the prediction and transfom it to numpy array
        shape = predictor(gray, rect)
        shape = face_utils.shape_to_np(shape)
        data.append(shape)
        cv2.putText(gray,"Calibrating...", bottomLeftCornerOfText, font, fontScale, fontColor,lineType)

        # Draw on our image, all the finded cordinate points (x,y) 
        for (x, y) in shape:
            cv2.circle(gray, (x, y), 2, (0, 255, 0), -1)

    # Show the image
    cv2_imshow(gray)

NameError: name 'Javascript' is not defined

In [ ]:
import numpy as np
import cv2
import random
from google.colab.patches import cv2_imshow


cap = cv2.VideoCapture(0)
i=0
while(True):
    ret, frame = cap.read()
    print(frame)
    i+=1
    cv2.imwrite('database/{index}.png'.format(index=i),frame)
    cv2_imshow(frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

None


error: ignored

In [ ]:
#Run Calibration
mean, std = calibration()

error: ignored

In [ ]:
#Run Demonstration
features, result = live()

In [ ]:
#Plot Results
features =np.vstack(features)
y = pd.DataFrame(features,columns=["EAR","MAR","Circularity","MOE","EAR_N","MAR_N","Circularity_N","MOE_N"])
y = y.drop(columns=["EAR_N","MAR_N","Circularity_N","MOE_N"])

x = y.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
y = pd.DataFrame(x_scaled,columns=["Eye Aspect Ratio","Mouth Aspect Ratio","Eye Circularity","Mouth over Eye"])


y ["Result"] = result


fig, (ax1, ax2) = plt.subplots(nrows=2,
                                ncols=1,
                                sharex=True,
                                sharey=False,
                                figsize=(15, 8))

ax1.set_title("Normalised Features")
#ax1.plot(y["Eye Aspect Ratio"])
#ax1.plot(y["Mouth Aspect Ratio"])
ax1.plot(y["Eye Circularity"])
ax1.plot(y["Mouth over Eye"])
ax1.legend(loc="best")
ax1.set_ylabel('Feature Value')


ax2.plot(y["Result"],marker = '.', color = "Black")
ax2.set_xlabel('Time (Frames Captured)')